name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Qt5/Qt6 (yaqti)
    # You may pin to the exact commit or the version.
    # uses: WillBrennan/yaqti@8182822afd102e931137d71da54f52a13597af8d
      uses: WillBrennan/yaqti@2021.07.29
      with:
    # Qt version to pick 5.15.2 or 6.2.1
        version: 6.2.0
    # install os; linux, windows, or mac
        os: windows
    # what platform are you installing for? desktop, winrt, android, or ios
        platform: desktop
    # what optional Qt modules to install? qtcharts, qtnetworkauth ect...

    - name: Visual Studio shell
    # You may pin to the exact commit or the version.
    # uses: egor-tensin/vs-shell@9a932a62d05192eae18ca370155cf877eecc2202
      uses: egor-tensin/vs-shell@v2
      with:
    # Target architecture
        arch: x64

    - name: build
      run: |
        dir C:\
        echo "---------"
        dir D:\
        echo "---------"
        dir ${{ github.workspace }}
        ${{ github.workspace }}\scripts\build_release.bat
        ${{ github.workspace }}\scripts\build_debug.bat
        
    - name: Create Release
      uses: actions/upload-artifact@v2
      with: |
        name: release
        path: ${{ github.workspace }}\build\release\TimeTable-Qt.exe
        
        name: debug
        path: ${{ github.workspace }}\build\debug\TimeTable-Qt.exe
      
