name: C/C++ CI

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - name: Install Qt
      # You may pin to the exact commit or the version.
      # uses: jurplel/install-qt-action@2d518188e746defd451af981c3c901f463d99e29
      uses: jurplel/install-qt-action@v3.2.1
      with:
        # Directory to install Qt
        dir: C:\
        # Version of Qt to install
        version: 6.5.1
        # Host platform
        host: windows
        # Target platform for build
        target: desktop
        # Architecture for Windows/Android
        arch: win64_msvc2019_64
        # Whether or not to install Qt dependencies on Linux
        install-deps: false # optional, default is true
        # Additional Qt modules to install

    - name: Visual Studio shell
    # You may pin to the exact commit or the version.
    # uses: egor-tensin/vs-shell@9a932a62d05192eae18ca370155cf877eecc2202
      uses: egor-tensin/vs-shell@v2
      with:
    # Target architecture
        arch: x64

    - name: build
      run: |
        dir C:\
        echo "---------"
        dir D:\
        echo "---------"
        dir ${{ github.workspace }}
        ${{ github.workspace }}\scripts\build_release.bat
        ${{ github.workspace }}\scripts\build_debug.bat
        
    - name: Create Release
      uses: actions/upload-artifact@v2
      with: |
        name: release
        path: ${{ github.workspace }}\build\release\TimeTable-Qt.exe
        
        name: debug
        path: ${{ github.workspace }}\build\debug\TimeTable-Qt.exe
      
